---
# default environment to deploy if not specific
env: "development"

# rocketchat.audit parameters
service_verbosity: 0

# cron job parameters
audit_email: "audit@example.com"
from_email: "rocketchat@example.com"
crontab: "55 23 * * *"
cron_verbosity: 2

# deployment parameters
deploy_dir: "/usr/local/bin/rocketchat.audit"
log_dir: "/var/log/rocketchat"
user: "rocketchat"
group: "rocketchat"
remote_user: "release"
