---
- name: "Deploy Rocket.Chat.Audit"
  vars_files:
    - config.yml
  hosts: "{{ env }}"
  remote_user: "{{ remote_user }}"
  become: true

  tasks:
  - name: "Ensure directories exist with correct permissions"
    file: path={{ item }} state=directory owner={{ user }} group={{ group }} mode=0755
    with_items:
    - "{{ audit_dir }}"
    - "{{ file_store }}"
    - "{{ file_archive }}"
    - "{{ backup_dir }}"
    - "{{ file_audit_dir }}"

  - name: "Install python dependencies"
    apt: name={{ item }} state=present
    with_items:
    - python-setuptools
    - python-pip

  - name: "Copy rocketchat.audit dependencies"
    copy: src=../requirements.txt dest=/tmp/requirements.txt
  - name: "Install rocketchat.audit dependencies"
    pip: requirements=/tmp/requirements.txt state=present

  - name: "Deploy rocketchat.audit script"
    copy: src=../rocketchat.audit.py dest={{ script_bin_dir }}/rocketchat.audit.py owner={{ user }} group={{ group }} mode=0755
    notify:
    - restart rocketchat.audit cron

  - name: "Deploy rocketchat.audit service"
    template: src=rocketchat.audit.conf.j2 dest=/etc/init/rocketchat.audit.conf

  - name: "Deploy rocketchat.audit cron"
    template: src=rocketchat.audit.cron.sh.j2 dest={{ cron_bin_dir }}/rocketchat.audit.cron.sh owner={{ user }} group={{ group }} mode=0755
  - name: "Configure rocketchat.audit crontab"
    cron: name=rocketchat.audit user={{ user }}
          minute={{ crontab.split(' ')[0] }} hour={{ crontab.split(' ')[1] }}
          day={{ crontab.split(' ')[2] }} month={{ crontab.split(' ')[3] }}
          weekday={{ crontab.split(' ')[4] }}
          job="{{ cron_bin_dir }}/rocketchat.audit.cron.sh >> {{ audit_dir }}/cron.log"
  - name: "Configure rocketchat.audit sudoers"
    template: src=rocketchat.audit.sudoers.j2 dest=/etc/sudoers.d/rocketchat-audit owner=root group=root mode=0440

  handlers:
  - name: restart rocketchat.audit
    service: name=rocketchat.audit state=restarted
